name: Continuous Integration

on: [push, workflow_dispatch]

concurrency:
  group: continuous-integration
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Cache LLVM and Clang
        id: cache-llvm
        uses: actions/cache@v3
        with:
          path: |
            C:/Program Files/LLVM
            ./llvm
          key: llvm-16.0.0

      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "16.0.0"
          cached: ${{ steps.cache-llvm.outputs.cache-hit }}

      - name: Get CMake
        uses: lukka/get-cmake@latest

      - name: Run vcpkg
        uses: lukka/run-vcpkg@v10
        with:
          vcpkgDirectory: "${{ github.workspace }}/external/vcpkg"
          vcpkgJsonGlob: "${{ github.workspace }}/vcpkg.json"

      - name: Run CMake
        uses: lukka/run-cmake@v10
        with:
          configurePreset: "configure-release-with-debug-info"
          configurePresetAdditionalArgs: '[`-DENABLE_CODE_COVERAGE=ON`]'
          buildPreset: "build-release-with-debug-info"
          buildPresetAdditionalArgs: '[`--target unit_tests`]'
          testPreset: "test-release-with-debug-info"

      - name: Code Coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
