name: Continuous Integration

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up Windows Includes Paths
        run: |
          # Set environment variables for Windows headers needed by Clang
          echo "WindowsIncludes=C:/Program Files (x86)/Windows Kits/10/Include/10.0.22621.0" >> $GITHUB_ENV

      - name: Get CMake
        uses: lukka/get-cmake@latest

      - name: Run vcpkg
        uses: lukka/run-vcpkg@v10
        with:
          vcpkgDirectory: "${{ github.workspace }}/external/vcpkg"
          vcpkgJsonGlob: "${{ github.workspace }}/vcpkg.json"

      - name: Run CMake
        uses: lukka/run-cmake@v10
        with:
          configurePreset: "ninja-multi-vcpkg"
          configurePresetAdditionalArgs: '[`-DENABLE_TESTING=ON`, `-DENABLE_CODE_COVERAGE=ON`]'
          buildPreset: "ninja-multi-vcpkg-debug"
          buildPresetAdditionalArgs: '[`--target unit_tests`]'
          testPreset: "ninja-multi-vcpkg-debug"
