name: Continuous Integration

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Get CMake
        uses: lukka/get-cmake@latest

      - name: Run vcpkg
        uses: lukka/run-vcpkg@v10
        with:
          vcpkgDirectory: "${{ github.workspace }}/external/vcpkg"
          vcpkgJsonGlob: "${{ github.workspace }}/vcpkg.json"

      - name: Run CMake
        uses: lukka/run-cmake@v10
        with:
          configurePreset: "ninja-configure"
          configurePresetAdditionalArgs: '[`-DENABLE_TESTING=ON`, `-DENABLE_CODE_COVERAGE=ON`]'
          buildPreset: "ninja-build-debug"
          buildPresetAdditionalArgs: '[`--target unit_tests`]'
          testPreset: "ninja-test-debug"

      - name: Code Coverage
        run: bash <(curl -s https://codecov.io/bash)
